//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEF6_SQLite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsiEntities : DbContext
    {
        public EsiEntities(string s)
            : base(s)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_ObjectInfoType> Table_ObjectInfoType { get; set; }
        public virtual DbSet<Table_ObjectType> Table_ObjectType { get; set; }
        public virtual DbSet<Table_PropertyType> Table_PropertyType { get; set; }
        public virtual DbSet<Table_SubItem> Table_SubItem { get; set; }
        public virtual DbSet<Table_SubItem_Info> Table_SubItem_Info { get; set; }
    }
}
