//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEF6_SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_SubItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_SubItem()
        {
            this.Table_SubItem_Info = new HashSet<Table_SubItem_Info>();
        }
    
        public long id { get; set; }
        public long id_ObjectInfoType { get; set; }
        public string Name { get; set; }
    
        public virtual Table_ObjectInfoType Table_ObjectInfoType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_SubItem_Info> Table_SubItem_Info { get; set; }
    }
}
