//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEF6_SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_ObjectInfoType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_ObjectInfoType()
        {
            this.Table_SubItem = new HashSet<Table_SubItem>();
        }
    
        public long id { get; set; }
        public Nullable<long> id_ObjectType { get; set; }
        public string DefaultString { get; set; }
        public string MinData { get; set; }
        public string MaxData { get; set; }
        public string DefaultData { get; set; }
        public string MinValue { get; set; }
        public string MaxValue { get; set; }
        public string DefaultValue { get; set; }
        public string Unit { get; set; }
    
        public virtual Table_ObjectType Table_ObjectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_SubItem> Table_SubItem { get; set; }
    }
}
